version: 0.2
phases:
  pre_build:
    commands:
      - echo Hola!
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  name: WarFile
  files:
    - target/demo-0.0.1-SNAPSHOT.war
  discard-paths: yes
