# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs: 
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: setup-yq
        uses: chrisdickinson/setup-yq@v1.0.0
      - name: Save branch name to file
        run: echo "${{ github.event.issue.body }}" > input.yaml
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.25.3
        with:
          # The Command which should be run
          cmd: "echo "hello: world" | yq .hello"
