# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs:
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"
    
      - name: Get branch name using yq
        uses: mikefarah/yq@v4.25.3
        with:
          cmd: echo ${{ github.event.issue.body }}" | yq '.BranchName'
