# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs:
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: echo "::set-output name=YQ_COMMAND::${{ github.event.issue.body }} | yq '.BranchName'"
    
      - name: Get branch name using yq
        uses: mikefarah/yq@v4.25.3
        with:
          cmd: ${{ steps.view-issue-information.outputs.YQ_COMMAND }}
