# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs: 
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Save branch name to file
        run: echo "${{ github.event.issue.body }}" > input.yaml
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.25.3
        id: getbranch
        with:
          # The Command which should be run
          cmd: "yq .BranchName | input.yaml"
      - name: Print Branch
        run: echo Found branch ${{ steps.getbranch.outputs.result }}
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ steps.getbranch.outputs.result }}'
