# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs:
  yq-input:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      yq_input: "${{ github.event.issue.body }} | yq '.BranchName'"
    steps:
    - id: step1
      run: echo "hello world"
      
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name using yq
        uses: mikefarah/yq@v4.25.3
        with:
          cmd: ${{ needs.yq-input.outputs.yq_input }}
