# This workflow checks for new issues using the new CD template
#

name: Setup CD for new Branch

on: issues

jobs: 
  newIssueCreated:
    runs-on: ubuntu-latest
    steps:
      - id: Set file
        run: echo "${{ github.event.issue.body }} > input.yaml
      - name: Get branch name using yq
        uses: mikefarah/yq@v4.25.3
        with:
          cmd: yq '.BranchName' input.yaml
