name: Branch Deleted

on:
  delete:
  workflow_dispatch:

jobs:
  onBranchDeleted:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: read
    # if: github.event.ref_type == 'branch'
    steps:
      # - name: Clean up
      #   run: |
      #     echo "Checking pipline cleanup for branch ${{ github.event.ref }}"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::384408301901:role/gitops-odic-source-Role-BLOZ4AX6UZ39

      - name: Check for pipeline existing
        run: |
          echo "::set-output name=PIPELINE_EXISTS::$(scripts/doesPipelineExist.sh featureX)"
        id: pipelineexists

      - name: Generate Issue file
        run: |
          echo 'Detected branch deletion: featureX\nShould we cleanup the CD pipeline?\nComment "Yes" to delete"' > issue-input.md
        if: ${{ steps.pipelineexists.outputs.PIPELINE_EXISTS }} == 1

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Cleanup CD for FeatureX
          content-filepath: ./issue-input.md
          labels: |
            cleanup-CD
        if: ${{ steps.pipelineexists.outputs.PIPELINE_EXISTS }} == 1
